### PR TITLE
[Backtracing][Docs] Add an explanation of the workings of the backtracer

### PR DESCRIPTION
**Pull request by al45tair**
Add some discussion of how the new external backtracer works and what options are available.

rdar://105394365

### CODE REVIEW

**Comment by al45tair** [comment]
This is part of a set of stacked PRs:

|  | PR                | Title                                                                      | Merges Into       |
|--|:------------------|:---------------------------------------------------------------------------|:------------------|
|  | apple/swift#63650 | [Backtracing] Add support for building target executables into libexec     | main              |
|  | al45tair/swift#8  | [Backtracing] Add support for looking up paths for auxiliary executables   | apple/swift#63650 |
|  | al45tair/swift#9  | [Backtracing][Runtime][Darwin] Add code to trigger the external backtracer | al45tair/swift#8  |
|  | al45tair/swift#10 | [Backtracing] Add _Backtracing library to the build                        | al45tair/swift#9  |
|  | al45tair/swift#11 | [Backtracing][Frontend] Add support for implicit import of _Backtracing    | al45tair/swift#10 |
|  | al45tair/swift#12 | [Backtracing] Add swift-backtrace to the build                             | al45tair/swift#11 |
|👉| al45tair/swift#13 | [Backtracing][Docs] Add an explanation of the workings of the backtracer   | al45tair/swift#12 |
|  | al45tair/swift#14 | [Backtracing] Add control over symbol caching                              | al45tair/swift#13 |

(Only the bottom PR will be able to run PR checks at any time. Please don't wait for the checks before review.)

**Comment by grynspan** [comment]
This information is very helpful. It would be nice to explain _how_ crash-catching works. It's not going to be obvious to Joe Randomface how Swift detects a crash and interposes its own diagnostic tools.

**Comment by al45tair** [comment]
> This information is very helpful. It would be nice to explain _how_ crash-catching works. It's not going to be obvious to Joe Randomface how Swift detects a crash and interposes its own diagnostic tools.

This was aimed more at users of Swift, which is why it doesn't talk about that.

I wonder whether we should have a text file with that information or just refer people to the code (which might have some comments in it to explain, perhaps).

**Review by weissi — APPROVED** [review]
Love it, awesome.

Some things I'd love to see mentioned:
- What signals does it hook?
- What things does it expect you to do/not do?

**Comment by al45tair** [comment]
> Some things I'd love to see mentioned:
> 
> * What signals does it hook?

I've added a list of what it handles right now.

> * What things does it expect you to do/not do?

I've added a couple of notes — basically, it behaves how you'd imagine; if you mess with the signal handlers, you may break it one way or another. I've also updated things lower down the PR stack to only install signal handlers and the alt stack if there isn't anything installed already (@mikeash pointed out that some other language runtime, maybe Java, catches `SIGSEGV` in order to avoid having `NULL` tests, and we don't want to break that).

I don't think the code has many expectations otherwise. We basically try to hand off to the external backtracer with the minimum of fuss.

**Review by Lukasa — APPROVED** [review]
Looks awesome, I love it. I don't think I have particular notes here. I do wonder if we want to be able to limit the signals for which handlers are installed (presumably by uninstalling them), but probably sufficient to have the documentation note in place.

**Pull request closed without merging**
